name: CI2

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events to branches matching refs/heads/releases/10
      - 'feature/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: github_action_test
          # options: >-
          #   --health-cmd="mysqladmin ping"
          #   --health-interval=10s
          #   --health-timeout=5s
          #   --health-retries=3
    env:
      DB_USER: root
      # DB_PASS: password
      DB_HOST: 127.0.0.1
      # DB_DB: cashare_cc_test
      DB_PORT: 3306

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler: default
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          bundle install --retry 3
          yarn install
      - name: DB prepare
        run: |
          sudo service mysql start
          bundle exec rake db:create
          bundle exec rake db:migrate
        env:
          DB_PORT: 3306
          RAILS_ENV: test
      - name: Run tests
        run: |
          rubocop

