name: CI2

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events to branches matching refs/heads/releases/10
      - 'feature/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: github_action_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: 12341234
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler: default
          bundler-cache: true
      - name: Install dependencies
        run: |
          bundle install --retry 3
          yarn install
          sudo service mysql start
          systemctl status mysql.service
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: DB prepare
        run: |
          echo '!!!!!!!!!!!!!'
          echo $DATABASE_HOST
          echo $DATABASE_PORT
          mysql -h 127.0.0.1 --port 3306 -u root -p 12341234 -e 'CREATE DATABASE IF NOT EXISTS github_action_test;'
        # bundle exec rake db:create
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
          DATABASE_HOST: 127.0.0.1
      - name: Run tests
        run: |
          bundle exec rake db:migrate
          bundle exec rubocop

